### ISSUE TITLE
`TestSave` hangs with python 3.13

### ISSUE THREAD

**Issue by ZedThree** [boutproject/xBOUT#304]
Some kind of issue with threading on python 3.13. `test_save_all` hangs and needs to be killed. Traceback from killing it:

```
python -m pytest -vv -k TestSave
============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.13.0, pytest-8.3.3, pluggy-1.5.0 -- /home/peter/Codes/BOUT++/xBOUT/.venv/bin/python
cachedir: .pytest_cache
rootdir: /home/peter/Codes/BOUT++/xBOUT
configfile: pyproject.toml
plugins: cov-6.0.0
collecting ... 
    skipping long tests, pass '--long' to enable
collected 798 items / 779 deselected / 19 selected                                                                                                                                                               

xbout/tests/test_boutdataset.py::TestSave::test_save_all ^C

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! KeyboardInterrupt !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/threading.py:359: KeyboardInterrupt
(to show a full traceback on KeyboardInterrupt use --full-trace)
============================================================================================ 779 deselected in 12.78s ============================================================================================
^CException ignored on threading shutdown:
Traceback (most recent call last):
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/threading.py", line 1534, in _shutdown
    atexit_call()
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/threading.py", line 1505, in <lambda>
    _threading_atexits.append(lambda: func(*arg, **kwargs))
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/threading.py", line 1092, in join
    self._handle.join(timeout)
KeyboardInterrupt: 
^CException ignored in atexit callback <bound method ThreadPoolExecutor.shutdown of <concurrent.futures.thread.ThreadPoolExecutor object at 0x7f87ebc8f8c0>>:
Traceback (most recent call last):
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/concurrent/futures/thread.py", line 238, in shutdown
    t.join()
  File "/home/peter/.local/share/uv/python/cpython-3.13.0-linux-x86_64-gnu/lib/python3.13/threading.py", line 1092, in join
    self._handle.join(timeout)
KeyboardInterrupt: 
```

I couldn't see any obvious issues on xarray or dask about this, and I couldn't immediately reproduce it manually (i.e. not in pytest)

**Comment by dschwoerer** [comment]
Can we add a timeout to pytest?
I think this issue is also seen in CI, where 3.13 is running into a timeout (but then no backtrace is generated)

Locally I do get segfaults instead 😇 
This looks like it is related to the not-thread-safe netcdf python library:

```
 python3.13 -m pytest -vv -k TestSave xbout --full-trace                                                                                                                                                             
=========================================================================================================== test session starts ============================================================================================================
platform linux -- Python 3.13.9, pytest-9.0.2, pluggy-1.6.0 -- /usr/bin/python3.13                                                                                                                                                          
cachedir: .pytest_cache                                                                                                                                                                                                                     
rootdir: /raven/u/dave/soft/xbout                                                                                                                                                                                                           
configfile: pyproject.toml                                                                                            
collecting ...                                                                                                        
    skipping long tests, pass '--long' to enable                                                                      
collected 797 items / 778 deselected / 19 selected                                                                                                                                                                                          
                                                                                                                                                                                                                                            
xbout/tests/test_boutdataset.py::TestSave::test_save_all PASSED                                                                                                                                                                      [  5%] 
xbout/tests/test_boutdataset.py::TestSave::test_reload_all[None] FAILED                                                                                                                                                              [ 10%] 
xbout/tests/test_boutdataset.py::TestSave::test_reload_all[toroidal] Fatal Python error: Segmentation fault           
                                                                                                                      
Thread 0x000014ebc05386c0 (most recent call first):                                                                                                                                                                                         
  File "/usr/local/lib/python3.13/site-packages/dask/diagnostics/progress.py", line 129 in _timer_func                                                                                                                                      
  File "/usr/lib64/python3.13/threading.py", line 994 in run                                                                                                                                                                                
  File "/usr/lib64/python3.13/threading.py", line 1043 in _bootstrap_inner                                                                                                                                                                  
  File "/usr/lib64/python3.13/threading.py", line 1014 in _bootstrap                                                  
                                                                                                                                                                                                                                            
Thread 0x000014e9e45e26c0 (most recent call first):                                                                                                                                                                                         
  File "/u/dave/.local/lib/python3.13/site-packages/xarray/backends/locks.py", line 231 in __enter__                                                                                                                                        
  File "/u/dave/.local/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 80 in __setitem__                                                                                                                                    
  File "/usr/local/lib/python3.13/site-packages/dask/array/core.py", line 4808 in load_store_chunk                    
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 758 in __call__                             
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 1078 in execute_graph                       
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 199 in _execute_subgraph                    
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 759 in __call__                                                                                                                                                   
  File "/usr/local/lib/python3.13/site-packages/dask/local.py", line 256 in execute_task                                                                                                                                                    
  File "/usr/local/lib/python3.13/site-packages/dask/local.py", line 270 in batch_execute_tasks                       
  File "/usr/lib64/python3.13/concurrent/futures/thread.py", line 59 in run                                                                                                                                                                 
  File "/usr/lib64/python3.13/concurrent/futures/thread.py", line 93 in _worker                                       
  File "/usr/lib64/python3.13/threading.py", line 994 in run                                                                                                                                                                                
  File "/usr/lib64/python3.13/threading.py", line 1043 in _bootstrap_inner                                                                                                                                                                  
  File "/usr/lib64/python3.13/threading.py", line 1014 in _bootstrap                                                                                                                                                                        
                                                                                                                      
Thread 0x000014e9e47e36c0 (most recent call first):                                                                   
  File "/u/dave/.local/lib/python3.13/site-packages/xarray/backends/locks.py", line 231 in __enter__                  
  File "/u/dave/.local/lib/python3.13/site-packages/xarray/backends/netCDF4_.py", line 80 in __setitem__                                                                                                                                    
  File "/usr/local/lib/python3.13/site-packages/dask/array/core.py", line 4808 in load_store_chunk                                                                                                                                          
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 758 in __call__                                                                                                                                                   
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 1078 in execute_graph                                                                                                                                             
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 199 in _execute_subgraph                    
  File "/usr/local/lib/python3.13/site-packages/dask/_task_spec.py", line 759 in __call__                                                                                                                                                   
  File "/usr/local/lib/python3.13/site-packages/dask/local.py", line 256 in execute_task                                                                                                                                                    
  File "/usr/local/lib/python3.13/site-packages/dask/local.py", line 270 in batch_execute_tasks                                                                                                                                             
  File "/usr/lib64/python3.13/concurrent/futures/thread.py", line 59 in run                                                                                                                                                                 
  File "/usr/lib64/python3.13/concurrent/futures/thread.py", line 93 in _worker                                                                                                                                                             
  File "/usr/lib64/python3.13/threading.py", line 994 in run                                                                                                                                                                                
  File "/usr/lib64/python3.13/threading.py", line 1043 in _bootstrap_inner                                                                                                                                                                  
  File "/usr/lib64/python3.13/threading.py", line 1014 in _bootstrap                               

[...]
```

@ZedThree can you repeat with `--full-trace` ?

**Comment by mikekryjak** [comment]
Can we close this now that we fixed the segfaults and other CI issues?
