### ISSUE TITLE
animate2D does not work with matplotlib 3.1.1.

### ISSUE THREAD

**Issue by gregordecristoforo** [boutproject/xBOUT#62]
The following example doesn't work with matplotlib 3.1.1 and never. It works with matplotlib 3.0.1 

array = np.random.randint(0, 100, size=(3, 4, 5))
xarray = xr.DataArray(array, dims=('t','x','y'), coords={'t': [10, 20,30], 'x': [1, 2,3,4],'y': [100, 200,300,400,500]})
dask_da = xarray.chunk(chunks={'t':3})
dask_da.bout.animate2D( animate_over='t', x='x', y='y')

my other package versions are:
animatplot                       0.5.0.dev1
matplotlib                        3.1.1 
xarray                              0.12.3+25.g86799b78
xBOUT                            0.1.0
xstorm                             0.1

The error message is the following: 

Traceback (most recent call last):
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 230, in saving
    yield self
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 572, in grab_frame
    buf.getvalue()))
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2542, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 829, in frombytes
    raise ValueError("not enough image data")
ValueError: not enough image data

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test_blob_label.py", line 32, in <module>
    dask_da.bout.animate2D( animate_over='t', x='x', y='y')
  File "/home/gregor/Documents/xBOUT/xbout/boutdataarray.py", line 83, in animate2D
    save_as=save_as, ax=ax, **kwargs)
  File "/home/gregor/Documents/xBOUT/xbout/plotting/animate.py", line 96, in animate_imshow
    anim.save(save_as + '.gif', writer=PillowWriter(fps=fps))
  File "/home/gregor/Documents/animatplot/animatplot/animation.py", line 187, in save
    self.animation.save(*args, **kwargs)
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 1156, in save
    writer.grab_frame(**savefig_kwargs)
  File "/home/gregor/anaconda3/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 232, in saving
    self.finish()
  File "/home/gregor/anaconda3/lib/python3.7/site-packages/matplotlib/animation.py", line 575, in finish
    self._frames[0].save(
IndexError: list index out of range

**Comment by rdoyle45** [comment]
I can't seem to reproduce this error, `animate2D` produces an animation fine using your commands.

May be an anaconda problem?

**Comment by johnomotani** [comment]
I cannot reporduce this error either. @gregordecristoforo - could you try to reproduce with animatplot-0.4.0 which is the newest stable release? If that works, it looks like a bug in the development version of animatplot. If it's that and you're feeling enthusiastic, you could try to make a minimal example with just numpy+animatplot; because we take `image_data = data.values` in animate2D, we convert the xarray/dask array to a numpy array, so I'd expect xarray and dask are not part of the problem.

**Comment by rdoyle45** [comment]
Cannot be reproduced. If this becomes an issue again a new thread can be set up.
