### ISSUE TITLE
Using xBOUT.collect in test-laplace fails on two processors

### ISSUE THREAD

**Issue by ZedThree** [boutproject/xBOUT#86]
I had to add `nx, ny, nz` to the benchmark file, but after that, I get the following:
```
      Checking variable flag0 ... Traceback (most recent call last):
  File "./runtest", line 48, in <module>
    result = collect(v, path="data", info=False)
  File "/home/peter/.local/lib/python3.7/site-packages/xbout/load.py", line 207, in collect
    keep_yboundaries=yguards, info=info)
  File "/home/peter/.local/lib/python3.7/site-packages/xbout/load.py", line 284, in _auto_open_mfboutdataset
    chunks=chunks)
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/backends/api.py", line 945, in open_mfdataset
    join=join,
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/combine.py", line 307, in _nested_combine
    join=join,
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/combine.py", line 198, in _combine_nd
    join=join,
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/combine.py", line 220, in _combine_all_along_first_dim
    datasets, dim, compat, data_vars, coords, fill_value, join
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/combine.py", line 248, in _combine_1d
    join=join,
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/concat.py", line 133, in concat
    return f(objs, dim, data_vars, coords, compat, positions, fill_value, join)
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/concat.py", line 340, in _dataset_concat
    var, to_merge[var], compat=compat, equals=equals.get(var, None)
  File "/home/peter/.local/lib/python3.7/site-packages/xarray/core/merge.py", line 143, in unique_variable
    f"conflicting values for variable {name!r} on objects to be combined. "
xarray.core.merge.MergeError: conflicting values for variable 'flag3ad' on objects to be combined. You can skip this check by specifying compat='override'.
```

**Comment by TomNicholas** [comment]
Ah I know what this is. If you have scalar data variables that are different in different files, xarray will complain when you try to combine those files together into a single dataset, because the result is ambiguous. There are loads of xarray options for how to handle this (including the `compat='override'` option) mentioned in the error, but if `flag3ad` is not an actual physical variable, it would be better to demote it to an attribute instead, like we already do for `walltime` etc. [here](https://github.com/boutproject/xBOUT/blob/36fb6e0bb8cc7f63d2e4c700905a30e0364d27f9/xbout/load.py#L471). The list of variables which we demote are specified [here](https://github.com/boutproject/xBOUT/blob/36fb6e0bb8cc7f63d2e4c700905a30e0364d27f9/xbout/load.py#L14), so try just adding `flag3ad` to that list @ZedThree ?

**Comment by johnomotani** [comment]
I managed to reproduce the error, but it's not an inconsistent scalar variable - `flag3ad` is a `Field3D`. It seems to be because `xbout.collect` doesn't close the files via `ds.close()`. `xarray`'s exception handling seems to be going a bit wrong...

**Comment by TomNicholas** [comment]
@ZedThree let us know if that fixes the problem in the BOUT tests
